server:
  port: 8001
spring:
  application:
    name: provider
  cloud:
    ###nocos\u6CE8\u518C\u4E2D\u5FC3
    nacos:
      discovery:
        server-addr: 39.105.30.146:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"